name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main  # Deploys when you push to main branch
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload site files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Root folder (where your index.html is)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
